apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: default
spec:
  secretName: nginx-cert-secret
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
  commonName: your-domain.com
  dnsNames:
    - your-domain.com
