apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: read-only
rules:
  - verbs: ["get", "list"]
    resources: ["pods", "services", "deployments"]
    apiGroups: [""]
